### ISSUE TITLE
Crear pagina login y maquetar seccion ingresar

### ISSUE THREAD

**Issue by FedericoLuna01** [FedericoLuna01/codo-a-codo#13]
![LOGIN](https://github.com/FedericoLuna01/codo-a-codo/assets/110360365/f4082225-dedc-4c48-bb12-824b7607623c)

**Comment by josersb** [comment]
que onda kevin, me dejas esta tarea para completarla, porque que yo había tomado la de crear el formulario de registrarse y ya lo termine, es para que ambas mantenga la misma estructura, te lo planteo a ver si te parece bien. O sino te fijas en como arme el código y ves que estructura use asi puedes replicarlo o modificarlo como mejor te parezca.
