### ISSUE TITLE
Crear header

### ISSUE THREAD

**Issue by FedericoLuna01** [FedericoLuna01/codo-a-codo#2]
Maquetar header.
![image](https://github.com/FedericoLuna01/codo-a-codo/assets/110360365/95956a50-c00c-4131-b607-e557838b4db0)

**Comment by FerJGit** [comment]
Listo el maquetado del header (este sería el código para el HTML, con los ... de la derecha y EDIT se ve) :
    <header>
        <nav>
            <picture>
                <a href="">
                    <img src="./img/branding/logo_light_horizontal.svg" alt="Isologoyipo de la marca Funkoshop">
                </a>
            </picture>
            <ul>
                <li><a href="./pages/shop.html">SHOP</a></li>
                <li><a href="./pages/contxt.html">CONTACTO</a></li>
                <li><a href="./pages/login.html">LOGIN</a></li>
                <li><a href="./pages/cart.html"><i class="fa-solid fa-cart-shopping"></i> CARRITO</a></li>
            </ul>
        </nav>
    </header>
