### ISSUE TITLE
Crear footer

### ISSUE THREAD

**Issue by FedericoLuna01** [FedericoLuna01/codo-a-codo#3]
Maquetar footer

![image](https://github.com/FedericoLuna01/codo-a-codo/assets/110360365/90f3fef9-9d5e-4569-9f65-ef0a40958905)

**Comment by FerJGit** [comment]
Este sería el del footer (con los ... y EDIT se ve) :

    <footer>
        <ul>
            <li>SHOP</li>
            <li>INGRESAR</li>
            <li>CONTACTO</li>
        </ul>
        <img src="./img/branding/logo_light_horizontal.svg" alt="Isologoyipo de la marca Funkoshop">
        <p>All rights reserved 2023 - Funkoshop &copy;</p>
    </footer>
